### ISSUE TITLE
ODBC Driver Assertion `stmt->Dbc->FirstStmt' Failed 

### ISSUE THREAD

**Issue by fuboat** [MonetDB/MonetDB#7306]
**Describe the bug**
ODBC Driver assertion failed

**To Reproduce**
command to start odbc client:
```sh
apt install unixodbc
# config MonetDB in $HOME/.odbc.ini
...
isql monetdb -v
```

Input the following statements:
```sql
SELECT avg(42) over (order by row_number() over ());
SELECT 1;
```

It will end up with an assertion failure:
```
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> SELECT avg(42) over (order by row_number() over ())
[37000][MonetDB][ODBC Driver 11.44.0]unexpected end of file
[ISQL]ERROR: Could not SQLPrepare
SQL> SELECT 1
isql: /root/MonetDB/clients/odbc/driver/ODBCStmt.c:194: destroyODBCStmt: Assertion `stmt->Dbc->FirstStmt' failed.
fish: “isql monetdb -v” terminated by signal SIGABRT (Abort)
```

**Expected behavior**
```
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL> SELECT avg(42) over (order by row_number() over ())
[37000][MonetDB][ODBC Driver 11.44.0]unexpected end of file
[ISQL]ERROR: Could not SQLPrepare
SQL> SELECT 1
+-----+
| %2  |
+-----+
| 1   |
+-----+
SQLRowCount returns 1
1 rows fetched
```

**Screenshots**

**Software versions**
 - ODBC Driver version number: MonetDB ODBC Driver 11.44.0
 - OS and version: Ubuntu 20.04, UnixODBC 2.3.6
 -  - MonetDB Server version number (I think that the server version doesn't matter): MonetDB Database Server v11.43.13 (hg id: ce33b6b12cd6)

**Issue labeling **
Make liberal use of the labels to characterise the issue topics. e.g. identify severity, version, etc..

**Comment by sjoerdmullender** [comment]
This has nothing to do with the ODBC driver.  Instead, this is a crash of the server during parsing/optimizing the first SELECT query.

**Comment by sjoerdmullender** [comment]
Ok, perhaps I shouldn't be so strict.  The ODBC driver should report the crash somehow and not itself also crash.

**Comment by PedroTadim** [comment]
I see at rel_order_by_column_exp, there's a check missing if the 'r' relation is set. It should fix this issue,

**Comment by sjoerdmullender** [comment]
If you add a check for `r` in the condition where it crahses (i.e. `if (r && ee->card > r->card)`) then it crashes somewhere else (in `exp_bin`).

**Comment by PedroTadim** [comment]
Ok, then further debugging is needed :)

**Comment by sjoerdmullender** [comment]
I fixed the ODBC part of the bug in the Jan2022 branch.  This will be merged into the default branch.

**Comment by PedroTadim** [comment]
The window function was not yet fixed. I have a fix for it, but I didn't push it yet because of a setting issue. A new issue should be open for it.

**Comment by njnes** [comment]
Fix checked into the main branch.
