### ISSUE TITLE
Aggregates returning string crash

### ISSUE THREAD

**Issue by msiomkin** [MonetDB/MonetDB#7360]
It's impossible to implement a C/C++ UDF returning a string and taking integral arguments. With aggregates things are even worse. It's impossible to implement an aggregate returning a string at all.

The following example works fine:

```sql
create or replace function my_test(stub string)
returns string
language c {
    #include <stdlib.h>

    result->initialize(result, stub.count);

    for (int i = 0; i < stub.count; i++) {
        result->data[i] = malloc(4);
        result->data[i][0] = 'a';
        result->data[i][1] = 'b';
        result->data[i][2] = 'c';
        result->data[i][3] = '\0';
    }
};

select pm_test('');
```

The same code crashes if we just change the parameter type to `int`:

```sql
create or replace function my_test(stub int)
returns string
language c {
    #include <stdlib.h>

    result->initialize(result, stub.count);

    for (int i = 0; i < stub.count; i++) {
        result->data[i] = malloc(4);
        result->data[i][0] = 'a';
        result->data[i][1] = 'b';
        result->data[i][2] = 'c';
        result->data[i][3] = '\0';
    }
};

select pm_test(1);
```

**Actual behaviour**
```
2023-03-12 16:34:50 ERR mydb[3386]: munmap_chunk(): invalid pointer
2023-03-12 16:34:53 MSG merovingian[3106]: database 'mydb' (-1) has crashed with signal SIGABRT (dumped core)
```

**Expected behavior**
```
+------+
| %2   |
+======+
| abc  |
+------+
1 tuple
```

Now let's try an aggregate. And, ok, let it takes a string:

```sql
create or replace aggregate my_test2(stub string)
returns string
language c {
    result->initialize(result, aggr_group.count);

    for (int i = 0; i < aggr_group.count; i++) {
        result->data[i] = malloc(4);
        result->data[i][0] = 'a';
        result->data[i][1] = 'b';
        result->data[i][2] = 'c';
        result->data[i][3] = '\0';
    }
};

select my_test2('') from any_table;
```

**Actual  behaviour:**
```
2023-03-12 16:40:29 MSG merovingian[3106]: database 'mydb' (-1) has crashed with signal SIGSEGV (dumped core)
```

**Expected behavior**
```
+------+
| %2   |
+======+
| abc  |
+------+
1 tuple
```

**Software versions**
```
[vagrant@centos8 mydbfarm]$ mserver5 --version
MonetDB 5 server 11.45.13 (hg id: 22b3cd795d) (64-bit, 128-bit integers)
This is an unreleased version
Copyright (c) 1993 - July 2008 CWI
Copyright (c) August 2008 - 2023 MonetDB B.V., all rights reserved
Visit https://www.monetdb.org/ for further information
Found 7.6GiB available memory, 16 available cpu cores
Libraries:
  libpcre: 8.42 2018-03-20
  libxml2: 2.9.7
Compiled by: vagrant@centos8.localdomain (x86_64-pc-linux-gnu)
Compilation: /usr/bin/cc
Linking    : /usr/bin/ld
```
 - OS and version: Centos 8
 - Compiled MonetDB from code

**Comment by njnes** [comment]
fixed the cudf code (double free). In sep2022 branch and newer.
Any reason for using the cudf over the normal c-extensibility?

**Comment by msiomkin** [comment]
After reading the documentation I thought C-UDF was the recommended way. Ok, generally I don't mind switching to regular UDFs. In fact I even thought about it because of this problem: https://stackoverflow.com/questions/75597450/query-the-db-from-a-monetdb-c-udf. But I have some questions:

1. Is there an up to date documentation? The following page is marked as outdated: https://www.monetdb.org/documentation-Sep2022/dev-guide/sql-extensions/user-defined-functions/

2. There's an example of a jitted aggregate C-UDF, but I couldn't find an example of how to make a regular aggregate UDF. Where can I have a look at how to do it?

**Comment by msiomkin** [comment]
I switched to branch branches/Sep2022. The version now is: 11.45.14 (hg id: 3a789ea975). The problem is still reproduced.

**Comment by njnes** [comment]
the github mirroring we do seems a bit behind. Hopefully tomorrow its better or just go for the real source via hg.

**Comment by njnes** [comment]
The page content is fine, maybe also look at https://www.monetdb.org/hg/MonetDB-extend/

**Comment by njnes** [comment]
https://www.monetdb.org/hg/MonetDB-extend/file/tip/gmean/README.rst
for the aggregate example

**Comment by msiomkin** [comment]
1. Thank you very much for the examples!

2. I downloaded the latest version https://www.monetdb.org/hg/MonetDB/rev/77ae02c05e69. Aggregates returning string seems to work now. It's great! But my first (non-aggregate) example still crashes:

```sql
create or replace function my_test(stub int)
returns string
language c {
    #include <stdlib.h>

    result->initialize(result, stub.count);

    for (int i = 0; i < stub.count; i++) {
        result->data[i] = malloc(4);
        result->data[i][0] = 'a';
        result->data[i][1] = 'b';
        result->data[i][2] = 'c';
        result->data[i][3] = '\0';
    }
};

select pm_test(1);
```

**Comment by msiomkin** [comment]
Aggregates returning string still crash if used with GROUP BY clause:

```sql
create or replace aggregate my_test2(stub string)
returns string
language c {
    result->initialize(result, aggr_group.count);

    for (int i = 0; i < aggr_group.count; i++) {
        result->data[i] = malloc(4);
        result->data[i][0] = 'a';
        result->data[i][1] = 'b';
        result->data[i][2] = 'c';
        result->data[i][3] = '\0';
    }
};

select my_test2('') from some_table group by some_column;
```

Result:

```
2023-03-14 12:02:16 ERR mydb[4037]: free(): invalid pointer
2023-03-14 12:02:21 MSG merovingian[2671]: database 'mydb' (4037) has crashed with signal SIGABRT (dumped core)
```

**Comment by njnes** [comment]
> 1. Thank you very much for the examples!
> 
>     2. I downloaded the latest version https://www.monetdb.org/hg/MonetDB/rev/77ae02c05e69. Aggregates returning string seems to work now. It's great! But my first (non-aggregate) example still crashes:
> 
> 
> ```sql
> create or replace function my_test(stub int)
> returns string
> language c {
>     #include <stdlib.h>
> 
>     result->initialize(result, stub.count);
> 
>     for (int i = 0; i < stub.count; i++) {
>         result->data[i] = malloc(4);
>         result->data[i][0] = 'a';
>         result->data[i][1] = 'b';
>         result->data[i][2] = 'c';
>         result->data[i][3] = '\0';
>     }
> };
> 
> select pm_test(1);
> ```

Why are you including stdlib.h?

**Comment by msiomkin** [comment]
I thought it was necessary for `malloc`. Does it matter?

P.S. As far as I can see `wrapped_GDK_zalloc_nojump` is called only for non grouped version, so unfortunately patch [86273f37609a](https://www.monetdb.org/hg/MonetDB/rev/86273f37609a) doesn't appeal to other cases :(

**Comment by njnes** [comment]
well the malloc gets redefined in the jit compiled code.

**Comment by njnes** [comment]
I've a new fix, which should make your cases work (and not leak any used memory). Also added tests for your cases

**Comment by msiomkin** [comment]
It looks like everything is ok now. Thanks!
