### ISSUE TITLE
Different date and time returns

### ISSUE THREAD

**Issue by alexandresilvawek** [MonetDB/MonetDB#7374]
**Describe the bug**
I identified 3 cases that I think are BUGs.

Case 1: The cast alters the result.
set time zone interval '-3' hour;
select current_timestamp, cast(current_timestamp as date);

Case 2: The cast alters the result.
set time zone interval '-3' hour;
select current_time, cast(current_time as time);

Case 3: The values are different and I think they should be the same.
set time zone interval '-3' hour;
select current_date, current_timestamp;

These commands need to be executed between 23:00 and 23:30 hours to ensure that the problems will occur.

Below you can see the result:
![suporte monetdb](https://github.com/MonetDB/MonetDB/assets/86444458/d3a078ad-5e72-4a73-b09d-357f03bcaa9b)

**To Reproduce**
Read the description and see the image above.

**Expected behavior**
The results of the two columns should always be the same (same date and time returned).

**Software versions**
 - MonetDB version number: 11.45.13
 - OS and version: Windows 10 64 bits

**Comment by mvdvm** [comment]
**current_time** returns a value of type: **time with time zone**.
**current_timestamp** returns a value of type: **timestamp with time zone**.
They are showing the time with time zone information.
When casting / converting them to **time** or **timestamp** or **date** types without time zone information as you did, they are adjusted to the local set **time zone**. Hence you will see differences.

See also: [temporal-types/#using-the-current-date-or-time](https://www.monetdb.org/documentation-Jun2023/user-guide/sql-manual/data-types/temporal-types/#using-the-current-date-or-time)

**Comment by alexandresilvawek** [comment]
Hi @mvdvm ,

Thanks for the clarifications.
I think I got it right.

Considering what you explained, I managed to solve case 2 this way:
_sql>set time zone interval '-3' hour;
operation successful
sql>select current_time, cast(current_time as time **with time zone**);
+-----------------------+----------------+
| %3                    | %2             |
+=======================+================+
| 15:49:34.193386-03:00 | 15:49:34-03:00 |
+-----------------------+----------------+
1 tuple_

But, how do I adjust case 1? I tried this way and it didn't work:
_sql>set time zone interval '-3' hour;
operation successful
sql>select current_timestamp, cast(current_timestamp as date **with time zone**);
syntax error in: "select current_timestamp, cast(current_timestamp as date with"_

And how do I adjust case 3?

**Comment by sjoerdmullender** [comment]
Dates don't have time zones, only times and timestamps.

**Comment by alexandresilvawek** [comment]
Hi @sjoerdmullender ,

And how do I get the current date considering my time zone?

**Comment by njnes** [comment]
The cast indeed converts first to internal time(stamp) without time zone, which for MonetDB is UTC, then selecting the data part etc. For stored values therefor timestamp with timezone is the correct approach.

If you have a db within one timezone then computing the correction could be done as follows:
select current_timestamp, cast(cast(current_timestamp as timestamp)+current_timezone as date);

**Comment by njnes** [comment]
this is now fixed in the cleanup_types branch, to be merged into default soon.

**Comment by njnes** [comment]
fixed in default, many time zone related fixes

**Comment by djxandytche** [comment]
Hello,

I just tested a newer version of MonetDB to see if these cases were resolved.
I noticed that case 1 and case 2 were resolved.
However, case 3 was not resolved.

See the image below:
![Captura de tela 2024-12-18 223801](https://github.com/user-attachments/assets/8511d35d-9363-4ce2-8260-554419b2adb3)

Can you help me with this?

Thanks.

**Comment by njnes** [comment]
current_date is based on system time (utc for monetdb). For dates in 'localtime', use select (current_timestamp as date);
