### ISSUE TITLE
Memory Leak Detected during Execution of Python UDF

### ISSUE THREAD

**Issue by KFilippopolitis** [MonetDB/MonetDB#7377]
**Bug Description**
There is a memory leak issue when executing a Python UDF. As the UDF runs multiple time and even though the artifacts created are deleted, the memory usage gradually increases over time.
This issue is most noticeable when running the UDF repeatedly.

**To Reproduce**
Setup the database using the database.sql.
Execute the python file leak_case.py.
Monitor the memory usage during the UDFs execution.
Observe that the memory consumption steadily increases over time.

**Expected behavior**
The memory usage during the execution of the Python UDF should remain stable, without any significant memory leaks or continuous memory growth.

**Actual Behavior**
The memory consumption gradually increases during the execution of the Python UDF, indicating the presence of a memory leak.
[leak_case.zip](https://github.com/MonetDB/MonetDB/files/11626969/leak_case.zip)

**Software versions**
MonetDB 11.45.13
Ubuntu 20.04

**Comment by njnes** [comment]
#2023-06-01 21:21:22: client5: createExceptionInternal: ERROR:   1. def pyfun(_columns,_column_types,_conn):
#2023-06-01 21:21:22: client5: createExceptionInternal: ERROR: > 2.   return _conn.execute('select * from results;')
#2023-06-01 21:21:22: client5: createExceptionInternal: ERROR:   3. 
#2023-06-01 21:21:22: client5: createExceptionInternal: ERROR: SQL Query Failed: SELECT: no such table 'results'

table results is missing?

**Comment by njnes** [comment]
Okay with t3 changed into results it seems to leak, deep in the call stack.

**Comment by njnes** [comment]
some leaks are fixed in the default now.

**Comment by njnes** [comment]
What feature is missing, to allow your queries to run without the python module?

**Comment by KFilippopolitis** [comment]
This is just a minimal case that we found that the leak still exists.
We do not use this specific udf.

**Comment by lsidir** [comment]
We use Python UDFs for ML tasks, so it is not a question of missing features. Each python udf is dynamicaly created and uses a variaty of ML python libraries.

**Comment by njnes** [comment]
Do you still notice a leak?

**Comment by lsidir** [comment]
Yes, from what they have told me even after the first fix there is still a
leak. Do you want us to test again the current ?

**Comment by njnes** [comment]
yes please test and report please.

**Comment by lsidir** [comment]
Ok will do ASAP. Thank you very much!

**Comment by KFilippopolitis** [comment]
I tried the case that I provided above  with the current master and the leak persist.

**Comment by ThanKarab** [comment]
Any updates on this one?

**Comment by njnes** [comment]
Fixed some more (small) leaks. On default, please test with version from the hg repo.

**Comment by njnes** [comment]
10    11,648,830 bytes                                                                                                                                                                    
 100    11,680,174 bytes                                                                                                                                                                    
1000    11,701,228 bytes                   
These are the possibly leaked bytes reported by valgrind for runs with 10, 100, 1000 queries.

**Comment by ThanKarab** [comment]
@njnes Are these values from the leaks that are still remaining?

**Comment by njnes** [comment]
these are the small (possibly leaks) remaining indeed between different run lengths (10, 100, and 1000)

**Comment by njnes** [comment]
problem is that python has ref-counting, that means there still are possibly objects marked as in use, but effectively dead. Problem is the tooling we use (valgrind/sanitizer) are insufficient without recompiling python ourselfs.
